### ISSUE TITLE
unable to restart redmine after plugin installation

### ISSUE THREAD

**Issue by rubiusus** [AlphaNodes/redmine_messenger#1]
Hi,
I have just installed redmine_messenger. But I cannot restart redmine container.
Some context:
- redmine running as a container in docker (official version 3.3)
- At installation, I mounted an external plugin folder:
> /volume4/docker/redmine/data/plugins:/usr/src/redmine/plugins

What I did in order to install this plugin:
entered the working redmine container "redminepro" and followed code as instrucions (I think)
> docker exec -it redminepro bash
> git clone git://github.com/alphanodes/redmine_messenger.git plugins/redmine_messenger

Installation seems fine
> Cloning into 'plugins/redmine_messenger'...
remote: Counting objects: 364, done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 364 (delta 70), reused 0 (delta 0), pack-reused 212
Receiving objects: 100% (364/364), 359.40 KiB | 488.00 KiB/s, done.
Resolving deltas: 100% (150/150), done.
Checking connectivity... done.

And I can see the new folder redmine_messenger and its files inside

But when I restart the container (redminepro) after very few seconds it stops.

If I delete the redmine_messenger folder, I am able to start redmine again.

I don't know if I am doing something wrong. It's the first time I install a plugin via command in the container. For those plugins that don't need to use commans but only put the folder in the plugins folder, I usually put it in the  /volume4/docker/redmine/data/plugins folder I created, restart the container and they work fine.

Thank you.

**Comment by alexandermeindl** [comment]
Can you provide me more information about your docker instance? E.g. which Ruby version is used? redmine_messenger requires 2.1.5 or newer. Do you have a log file with an error message?

**Comment by rubiusus** [comment]
I hope I am checking in the right place. In my redmine container I can find these details:
Enviroment variables (I've picked the ones I guess are relevant):
ruby_major 2.2
ruby_version 2.2.7
rubygems_version 2.6.12
bundler_version 1.14.6
gosu_version 1.7
rails_env production
redmine_version 3.3.3

Is there another way to check the data about Ruby you asked for?
And about the log file, could you tell me where can I get it?

Thank you.

**Comment by alexandermeindl** [comment]
Thanks for this information, everything looks good. Hmm. Do you use a public docker image, which I can download somewhere for tests?

**Comment by rubiusus** [comment]
I am using the docker installed in my synology 415+ server

**Comment by alexandermeindl** [comment]
I mean the docker image file, not docker itself. Is this your docker image: https://github.com/sameersbn/docker-redmine ?

**Comment by rubiusus** [comment]
Ah, it's the official one: https://hub.docker.com/_/redmine/
Do you suggest the sameersnb instead? I thought it was not updated for a while but since I am new to docker, maybe I misundertood

**Comment by alexandermeindl** [comment]
No, let me check it. I do not use docker at the moment. I'll test it with your "offical" image and let you know my results.

**Comment by alexandermeindl** [comment]
I fixed the problem. Please try it again, it should work now.
