### ISSUE TITLE
Could not set persian channel names at project level

### ISSUE THREAD

**Issue by idanielblake** [AlphaNodes/redmine_messenger#11]
Hello
Our channel names are mostly in persian. I tried to set a project channel name to "تست" but I got this error:

Updating failed.Mysql2::Error: Incorrect string value: '\xD8\xAA\xD8\xB3\xD8\xAA' for column 'messenger_channel' at row 1: UPDATE `messenger_settings` SET `messenger_channel` = 'تست' WHERE `messenger_settings`.`id` = 1

any idea?
Thank you

**Comment by alexandermeindl** [comment]
I suppose, it is the same problem as it is described here: http://www.redmine.org/issues/21398.

**Comment by alexandermeindl** [comment]
No further feedback, I close this issue for now.
