### ISSUE TITLE
Please replace "bundle update" to "bundle install" in your readme

### ISSUE THREAD

**Issue by phpony** [alphanodes/redmine_messenger#112]
Do you realize that running `bundle update` will update all gems in the project, that in certain installations (debian's apt redmine) will completely destroy the whole rake setup with unsupported versions installed over bundled apt versions so only a hours of manual removal work for all this new gems and restoring the apt ones could solve the problem? 

Please change `bundle update` to `bundle install`. That'll save a lot of time for others. :cry:

**Comment by alexandermeindl** [comment]
Thanks for your remark. I changed it.
