### ISSUE TITLE
Unable to install plugins

### ISSUE THREAD

**Issue by Mukesh90v** [AlphaNodes/redmine_messenger#18]
I'm trying to install the "Messenger plugin for Redmine"for the rocket chat. But then after at a time execute this command getting errors
bundle exec rake redmine:plugins:migrate RAILS_ENV=production

### LoadError: cannot load such file -- rspec/core
/opt/redmine/plugins/easyproject/easy_plugins/easy_extensions/lib/tasks/tests.rake:3:in `<top (required)>'
/opt/redmine/plugins/easyproject/lib/tasks/easyproject.rake:1:in `block in <top (required)>'
/opt/redmine/plugins/easyproject/lib/tasks/easyproject.rake:1:in `each'
/opt/redmine/plugins/easyproject/lib/tasks/easyproject.rake:1:in `<top (required)>'
/opt/redmine/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/opt/redmine/lib/tasks/redmine.rake:194:in `each'
/opt/redmine/lib/tasks/redmine.rake:194:in `<top (required)>'
/opt/redmine/Rakefile:7:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)

**Comment by alexandermeindl** [comment]
This looks like a problem with easyproject. We do not use this plugin, therefore we cannot test it.

**Comment by alexandermeindl** [comment]
No further feedback for more than a year - I close this issue. Feel free to reopen it, if required.
