### ISSUE TITLE
Error on migration step in installation process

### ISSUE THREAD

**Issue by lismateusz** [AlphaNodes/redmine_messenger#22]
Context:

I've been trying to install the plugin, but during the migration command (`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`) I get the following error:

Error:

> An error occurred while loading the routes definition of redmine_messenger plugin (/<path_to_redmine>/plugins/redmine_messenger/config/routes.rb): (eval):7: unknown type of %string
  resource :messenger_setting, only: %i[show update]
                                        ^
(eval):7: syntax error, unexpected $end
  resource :messenger_setting, only: %i[show update]

Redmine installation details:
-   Redmine version                3.0.3.stable
-   Ruby version                   2.2.2-p95 (2015-04-13) [x86_64-linux-gnu]
-   Rails version                  4.2.1
-   Environment                    production
-   Database adapter               Mysql2

**Comment by alexandermeindl** [comment]
Hi,
this error occurs with very old ruby versions, usually (older then 2.0). Are you sure, these installation details with Ruby 2.2.2 is the same installation, where you tried redmine_messenger plugin? If this is really the case, my only guess would be there is a encoding problem with /plugins/redmine_messenger/config/routes.rb. Mabye a fresh "git clone" of the redmine_messenger plugin can help.

**Comment by alexandermeindl** [comment]
I made a test with ruby 2.2.x and Redmine 3.0.3 without the problem, you got, see 
<img width="583" alt="test-env" src="https://user-images.githubusercontent.com/205221/47033153-62468380-d174-11e8-9d0b-9e1fc3514792.png">

**Comment by lismateusz** [comment]
Thank you for your answers. You are absolutely right about incorrect version of the ruby. Default bundle for command line was linked to ruby 1.9.1, while bundle for ruby 2.2.0 is also installed and available in $PATH as bundle2.2 alias. Using bundle2.2 the installation of the plugin was successful.

**Comment by alexandermeindl** [comment]
Thanks for you feedback.
