### ISSUE TITLE
Special characters are not properly rendered in the Rocket.Chat

### ISSUE THREAD

**Issue by nopynoop** [AlphaNodes/redmine_messenger#23]
I made a screenshot:

![2018-10-17_15-58-02](https://user-images.githubusercontent.com/25570106/47091581-71393e80-d225-11e8-97e0-8d9c73865463.png)

**Comment by Zuko** [comment]
I have same problem ;(

**Comment by ZerooCool** [comment]
+1 with Slack

**Comment by Sir-Will** [comment]
Same issue here with slack:
![](https://i.imgur.com/WdMcshS.png)

I didn't have that issue with redmine_slack (https://github.com/sciyoshi/redmine-slack).

**Comment by ZerooCool** [comment]
I have with redmine_slack, but, my last test date from 11 April.

**Comment by alexandermeindl** [comment]
See #38 for fix.
