### ISSUE TITLE
404 at plugin config in latest version (ver.1.0.3)

### ISSUE THREAD

**Issue by tykep** [AlphaNodes/redmine_messenger#26]
In these few days, I have tried to use this plugin (latest version 1.0.3) with Bitnami Redmine Stack (Windows). The install proccess has no problem, but after installing I always get 404 error from the config link of this plugin. I've tried many versions of Bitnami, but it doesn't change the situation. Finaly, it works when I revert the version of this plugin to 1.0.0. ( I've not tried 1.0.1 or 1.02.)

I found this problem with the environment as bellow:
OS: Windows 10 Home
Redmine: Bitnami Redmine Stack 3.4.2-4
https://downloads.bitnami.com/files/stacks/redmine/3.4.2-4/bitnami-redmine-3.4.2-4-windows-installer.exe

I hope this information would be useful for you.

**Comment by ZerooCool** [comment]
For my 404 error, with linux, i have rename the deposit once it is deposited on the server.
Use the  _ 
Not use -

Example :
cd redmine-4.0-stable/
cd plugins/
wget https://github.com/AlphaNodes/redmine_messenger/archive/master.zip
unzip master.zip
mv redmine_messenger-master/ redmine_messenger/

**Comment by karl-in-office** [comment]
@tykep 
I also have the same issue and have tried different versions. 
In my case, 
- master branch
NG
- 1.0.2
NG
- 1.0.1
OK
- 1.0.0
OK

**Comment by alexandermeindl** [comment]
Make sure you used installation instruction https://github.com/AlphaNodes/redmine_messenger#installation and your plugin directory is named "redmine_messenger". It is also important to restart your application server after updating the plugin.
