### ISSUE TITLE
Redmine 4 compatibility

### ISSUE THREAD

**Issue by majkinetor** [AlphaNodes/redmine_messenger#27]
Any plans ?

**Comment by alexandermeindl** [comment]
Do you have any problems with Redmine 4 and redmine_messenger? It should already work.

**Comment by majkinetor** [comment]
I didn't try, there is no mention of v4 in docs.

Thanks for quick info, I will test it now.

**Comment by xurizaemon** [comment]
How'd you go @majkinetor ?

**Comment by xurizaemon** [comment]
Upgraded to Redmine 4.0.2 with this plugin @ 58b4a890c, notifications were sent fine to Rocket.chat. Thanks @alexandermeindl, IMO this can be closed.

README says ["Redmine >= 3.0.0"](https://github.com/AlphaNodes/redmine_messenger#requirements), you could specifically mention it's been tested with 4.0 to reassure people if you wanted I guess?
