### ISSUE TITLE
UP locales with a fr.yml file

### ISSUE THREAD

**Issue by ZerooCool** [AlphaNodes/redmine_messenger#37]
UP locales with a fr.yml file

I can't pull request. Failure the travis CI build failed.

Can you merge my last locale file fr.yml ?

**Comment by alexandermeindl** [comment]
I merged #36. Thanks for contributing!

**Comment by ZerooCool** [comment]
Thank you for this merge.

If I have to change it in the future, it will be done here to start, then, pushed on the Github.

My original file fr.yml : https://wiki.visionduweb.fr/index.php?title=Installer_Redmine_sur_Debian#Changer_la_langue_du_message_envoy.C3.A9_sur_Slack

**Comment by ZerooCool** [comment]
New french version 2020 : 
https://github.com/AlphaNodes/redmine_messenger/pull/46/commits/6fa21f364886f2c5b44ce2c231c944a2d6662cee

**Comment by ZerooCool** [comment]
Up : https://github.com/AlphaNodes/redmine_messenger/pull/59
