### ISSUE TITLE
plugin doesnt work on bitnami redmine stack

### ISSUE THREAD

**Issue by silitho** [AlphaNodes/redmine_messenger#4]
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.1.10-p492 (2016-04-01) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

after installation I can find the plugin in admin/plugins, I can configure the plugin, but if I switch to the project configuration I got a redmine 500 Error

and if I create a new ticket I got the same error

**Comment by alexandermeindl** [comment]
Thanks for reporting it. Can you post the log to this error?

**Comment by silitho** [comment]
where can I find this log?

**Comment by alexandermeindl** [comment]
I do not use Bitnami, but I found some information to log files here: https://community.bitnami.com/t/bitnami-redmine-does-not-start-where-is-the-log-file/44528/4

If this information is right, you find it in file installdir/apps/redmine/htdocs/log/production.log

**Comment by silitho** [comment]
ok, here is a snippet of the log. 
the reason for the error ist the clear, but how can I install this plugin correct (I did the steps mentioned here) 

-------------------------------------------------------------------

ActionView::Template::Error (Mysql2::Error: Table 'bitnami_redmine.messenger_settings' doesn't exist: SHOW FULL FIELDS FROM `messenger_settings`):
    1: 
    2: <div class="box tabular messenger_settings">
    3:   <%
    4:     @messenger_setting = MessengerSetting.find_or_create(@project.id)
    5: %>
    6: 
    7: <%= labelled_form_for :setting, @messenger_setting,
  plugins/redmine_messenger/app/models/messenger_setting.rb:52:in `find_or_create'
  plugins/redmine_messenger/app/views/messenger_settings/_show.html.erb:4:in `_plugins_redmine_messenger_app_views_messenger_settings__show_html_erb___1426594535409698211_70157403215440'

**Comment by alexandermeindl** [comment]
This looks like there is no database table messenger_settings in your database. Did you run installation as described here: https://github.com/AlphaNodes/redmine_messenger#installation ?

**Comment by silitho** [comment]
yes, 
but I cloned it not to $REDMINE_ROOT/plugins/redmine_messenger
the plugin directory on bitnami stack is ~/apps/redmine/htdocs/plugins

**Comment by alexandermeindl** [comment]
The important command: 

> bundle exec rake db:migrate_plugins

This creates the database structure, which is missing on your installation.

**Comment by silitho** [comment]
I run this `bundle exec ...` command, but I'm not sure if it runs without errors

**Comment by silitho** [comment]
I found the problem: the output of `bundle exec ...` says:

> (in /opt/bitnami/apps/redmine/htdocs)
> rake aborted!
> Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

So what can I do now?

**Comment by alexandermeindl** [comment]
Try to use:

`bundle exec rake db:migrate_plugins RAILS_ENV=production`

**Comment by silitho** [comment]
**ok, it works. thank you very much.**

here is the output of the `bundle exec ...` with the note 

> db:migrate_plugins has been deprecated

(in /opt/bitnami/apps/redmine/htdocs)
Rails Error: Unable to access log file. Please ensure that /opt/bitnami/apps/redmine/htdocs/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /opt/bitnami/apps/redmine/htdocs/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Migrating to CreateMessengerSettings (1)

Note: The rake task db:migrate_plugins has been deprecated, please use the replacement version redmine:plugins:migrate
Migrating redmine_messenger (Redmine Messenger)...
== 1 CreateMessengerSettings: migrating =======================================
-- create_table(:messenger_settings)
   -> 0.0201s
== 1 CreateMessengerSettings: migrated (0.0202s) ==============================
