### ISSUE TITLE
Is it possible to show Status on Issue Updates?

### ISSUE THREAD

**Issue by nopynoop** [AlphaNodes/redmine_messenger#40]
It would good to see if the issue status has been updated, especially for closed issues.

Now users need to manually check what happened to the status (if closed, in-process or nothing changed).

**Comment by Ludofloria** [comment]
In `lib/redmine_messenger/patches/issue_patch.rb`, around line 70, replace
`if status_id != status_id_was`
by
`if status != status_was`
Restart redmine, and the status will be shown when updating ;)

**Comment by nopynoop** [comment]
Thank you. It worked!

**Comment by alexandermeindl** [comment]
A fix for status and priority is in master branch available.

**Comment by alexandermeindl** [comment]
Hi nopynoop,

could you test, if the latest update fixed you problem?

**Comment by cundd** [comment]
It works very nicely in our installation

**Comment by alexandermeindl** [comment]
Hi @cundd,

thanks for feedback!
