### ISSUE TITLE
Bug with time for a redmine issue to slack

### ISSUE THREAD

**Issue by ZerooCool** [AlphaNodes/redmine_messenger#50]
Time for a redmine issue
0:20 (minutes)

say to slack :
Temps estimé.
0.3333333333333333

Is it possible to have a more suitable rendering?

**Comment by rNoz** [comment]
You can have more suitable renderings (eg 0:20, 20m, etc). Have a look my repo, specifically https://github.com/rNoz/redshape/blob/master/render/datetime.js and everything that uses it for some inspiration (or  direct usage).

**Comment by alexandermeindl** [comment]
Thanks for reporting this! It is fixed with my last commit to master branch.
