### ISSUE TITLE
Add a title to block 1 of the configuration

### ISSUE THREAD

**Issue by ZerooCool** [AlphaNodes/redmine_messenger#53]
https://redmine.domaine.fr/projects/project_name/settings/messenger

The screen is divided into 3 parts, the second is called "requests" and the third is "wiki".

A name should be added to the first part, such as "Configure the incoming Webhook".

Then add an entry in the 4 language files.

**Comment by alexandermeindl** [comment]
Hi @ZerooCool 

thanks for the hint. I added it with my last commit.

**Comment by ZerooCool** [comment]
Ok, i look.

**Comment by ZerooCool** [comment]
I propose : https://github.com/AlphaNodes/redmine_messenger/pull/54

**Comment by ZerooCool** [comment]
Ok for me ! Nice.

[Resolved]
