### ISSUE TITLE
unable to ignore description in update issue

### ISSUE THREAD

**Issue by s-tkt** [AlphaNodes/redmine_messenger#61]
With messenger v1.0.6, mattermost v5.19.0 and redmein v4.0.4, description is included to messages though "Description in update issue?" field is set as false.

**Comment by alexandermeindl** [comment]
Hi @s-tkt 

Thanks for reporting this bug. I fixed it with my last commit. Let me know, if that solved your problem.

**Comment by s-tkt** [comment]
I thank very  much for your rapid fix. Everything work actually. A lot of thanks for this plugin.
