### ISSUE TITLE
Help wanted: "config.i18n.fallbacks = [I18n.default_locale]" i18n version problem.

### ISSUE THREAD

**Issue by konpega** [AlphaNodes/redmine_messenger#67]
I got a warning after bundle install. I am using RedminePlusAgile 4.1.0-8. What should I do?

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.5.7-p206 (2019-10-01) [x64-mingw32]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.25.0
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.12
  redmine_issues_tree            0.0.14
  redmine_monitoring_controlling 0.1.1
  redmine_people                 1.4.2
  redmine_smile_togglesidebar    1.0.7

HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

If you are upgrading your Rails application from an older version of Rails:

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.

If you are starting a NEW Rails application, you can ignore this notice.

For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

Post-install message from nokogiri:
Nokogiri is built with the packaged libraries: libxml2-2.9.10, libxslt-1.1.34, z
lib-1.2.11, libiconv-1.15.

**Comment by alexandermeindl** [comment]
I close this issue, because Redmine 4.1 is no longer supported by this plugin. Please try a newer Redmine version. If this problem still exists, please reopen this issue.
