### ISSUE TITLE
Mysql2::Error: Table 'agile_sprints' already exists:

### ISSUE THREAD

**Issue by pauloriply** [AlphaNodes/redmine_messenger#70]
Hi, i have a clean installation of redmine with this conf
===============================================================================
Environment:
  Redmine version                4.1.1.stable.19852
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.7
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.5.3
  redmine_checklists             3.1.16
  redmine_contacts               4.3.0
  redmine_contacts_helpdesk      4.1.8
  redmine_contacts_invoices      4.2.3
  redmine_crm_mailchimp          1.0.4
  redmine_finance                2.1.7
  redmine_people                 1.5.1
  redmine_products               2.1.2
  redmine_questions              1.0.2
  redmine_reporter               1.0.3
  redmine_resources              1.0.2
  redmine_zenedit                1.0.3

===============================================================================
when trying to install your plugin, the following happens:
`
var/data/redmine/4.1-stable/plugins/redmine_contacts/init.rb:29: warning: already initialized constant FCSV
/var/data/redmine/4.1-stable/plugins/redmine_agile/init.rb:29: warning: previous definition of FCSV was here
== 6 CreateAgileSprints: migrating ============================================
-- create_table(:agile_sprints, {:options=>"ENGINE=InnoDB", :id=>:integer})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'agile_sprints' already exists: CREATE TABLE `agile_sprints` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `project_id` int, `name` varchar(255) NOT NULL, `description` text, `status` int DEFAULT 0 NOT NULL, `start_date` date NOT NULL, `end_date` date NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:871:in `block in method_missing'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:840:in `block in say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:840:in `say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:860:in `method_missing'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration/compatibility.rb:32:in `create_table'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration/compatibility.rb:73:in `create_table'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration/compatibility.rb:141:in `create_table'
/var/data/redmine/4.1-stable/plugins/redmine_agile/db/migrate/006_create_agile_sprints.rb:22:in `change'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:814:in `exec_migration'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:797:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:796:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:510:in `up'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:542:in `migrate_plugin'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:483:in `migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:497:in `block in migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:496:in `each'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:496:in `migrate'
/var/data/redmine/4.1-stable/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'agile_sprints' already exists: CREATE TABLE `agile_sprints` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `project_id` int, `name` varchar(255) NOT NULL, `description` text, `status` int DEFAULT 0 NOT NULL, `start_date` date NOT NULL, `end_date` date NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:871:in `block in method_missing'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:840:in `block in say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:840:in `say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:860:in `method_missing'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration/compatibility.rb:32:in `create_table'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration/compatibility.rb:73:in `create_table'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration/compatibility.rb:141:in `create_table'
/var/data/redmine/4.1-stable/plugins/redmine_agile/db/migrate/006_create_agile_sprints.rb:22:in `change'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:814:in `exec_migration'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:797:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:796:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:510:in `up'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:542:in `migrate_plugin'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:483:in `migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:497:in `block in migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:496:in `each'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:496:in `migrate'
/var/data/redmine/4.1-stable/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

Caused by:
Mysql2::Error: Table 'agile_sprints' already exists
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:311:in `create_table'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:871:in `block in method_missing'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:840:in `block in say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:840:in `say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:860:in `method_missing'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration/compatibility.rb:32:in `create_table'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration/compatibility.rb:73:in `create_table'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration/compatibility.rb:141:in `create_table'
/var/data/redmine/4.1-stable/plugins/redmine_agile/db/migrate/006_create_agile_sprints.rb:22:in `change'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:814:in `exec_migration'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:797:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:796:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:977:in `migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1345:in `ddl_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1210:in `migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:510:in `up'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:1011:in `migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:542:in `migrate_plugin'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:483:in `migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:497:in `block in migrate'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:496:in `each'
/var/data/redmine/4.1-stable/lib/redmine/plugin.rb:496:in `migrate'
/var/data/redmine/4.1-stable/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
`

**Comment by alexandermeindl** [comment]
This is not a problem with this plugin. It looks like redmine_agile causes your error message.
