### ISSUE TITLE
Project link is not properly formatted on Slack

### ISSUE THREAD

**Issue by iquiw** [AlphaNodes/redmine_messenger#75]
![image](https://user-images.githubusercontent.com/238681/91660881-646d1d80-eb13-11ea-9cdf-ed72360d357d.png)

The link seems to be formatted as Markdown, but it is displayed as is.

**Comment by iquiw** [comment]
I think I could fix it for Slack, but I don't know about other messengers...

**Comment by mlocke317** [comment]
I am having the same issue in Synology Chat. Plugin works well, but project url ends with  ")" making it an invalid link.

**Comment by urinal-cake** [comment]
Can confirm this occurs on plugin version 1.0.12 loaded on Redmine version 4.2.6
