### ISSUE TITLE
Incorrect redmine links

### ISSUE THREAD

**Issue by Siemir** [AlphaNodes/redmine_messenger#9]
I have noticed that links that are generated for issues and projects are wrong when base URL for Redmine installation is in a folder. In my case main URL is "domain.com/z" leading to links like "domain.com/z/z/projects..." and "domain.com/z/z/issues..." which of course do not work at all.

Currently I have changed main URL in Redmine installation to "domain.com" which fortunately does not break anything, but I think it should be fixed here.

**Comment by alexandermeindl** [comment]
I can reproduce this problem. If you have a PR, I'll merge it. Otherwise I'll take a look at it, but this can take some time.

**Comment by moriyas1984** [comment]
Are there any update about this problem?

This plugin is the best solution to share activities on Redmine to Rocket.chat. I recently stated to use it instead of redmine_slack.

I'm eager to fix the bug:)
Thanks.

**Comment by alexandermeindl** [comment]
Can you check, if it works now with my latest update?

**Comment by Siemir** [comment]
Works great with my Mattermost server.

**Comment by alexandermeindl** [comment]
@Siemir great to hear!

@moriyas1984 let me know, if it working for you, too - before I close this issue.

**Comment by moriyas1984** [comment]
It works in my Redmine!
Thank you for your prompt and great work!

**Comment by alexandermeindl** [comment]
Thanks for your feedback!
