### ISSUE TITLE
RC shows "<br/> instead of linebreaks

### ISSUE THREAD

**Issue by kiilo** [AlphaNodes/redmine_messenger#90]
filed a bug at rocketChat:
* https://github.com/RocketChat/Rocket.Chat/issues/22734

maybe a solution is possible from plugin side 
maybe a output format selection for markdown / text / html?

![screenshot-chat psychologie uzh ch-2021 07 22-14_42_42](https://user-images.githubusercontent.com/271145/126645956-fbea7a54-289b-4845-9135-ef88b89d5464.png)

have some fixes for markdown RC url issues in exchange ;-)

Best
k.

**Comment by ankar84** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/22701

**Comment by kiilo** [comment]
thanks - solved in 3.17.0
