### ISSUE TITLE
Rocketchat integration no longer working

### ISSUE THREAD

**Issue by Trans-IP** [AlphaNodes/redmine_messenger#95]
For a few months now my plugin has stopped working and I have just started looking into it more deeply.

See: https://github.com/RocketChat/Rocket.Chat/issues/23208  for context.

I keep getting"status":400 on the response from the server once the payload is sent. I upgraded to the latest version of the plugin and upgraded the rocketchat server serveral times with no change in behaviour. 

Rocketchat Version
4.3.0
Apps Engine Version
1.29.0
Node Version
v12.18.4
Database Migration
252 (December 29, 2021 4:12 PM)
MongoDB
5.0.5 / wiredTiger (oplog Enabled)

**Comment by alexandermeindl** [comment]
I cannot reproduce this problem. I use Rocket.Chat 4.3.0 with latest redmine_messenger without problems. Please check your settings for incoming hooks in your Rocket.Chat configuration (e.g. permissions).

**Comment by Trans-IP** [comment]
Thanks for the reply.  I hadn't changed anything when it broke, only did an upgrade of the Rocketchat server.  The integration seems standard and the users etc all exist.  Let me see if I can find something else.

**Comment by alexandermeindl** [comment]
Some Rocket.Chat updates before, we had to adjust permissions in Rocket.Chat. Don't ask me what permission that was. On redmine_messenger side we cannot solve your problem.

**Comment by Trans-IP** [comment]
This is what I see as Permissions (the user is a bot and doesn't have the first 2):

![image](https://user-images.githubusercontent.com/8602677/148257007-88a59770-558d-4edb-be1d-9a8193acf0a2.png)

And this is what I see as Settings:

![image](https://user-images.githubusercontent.com/8602677/148257210-98f893af-a113-4e69-b3e8-41d07d933d1e.png)

**Comment by Trans-IP** [comment]
Thanks for the hint.  I found the solution based on a release note:

https://github.com/RocketChat/Rocket.Chat/releases/tag/4.0.0-rc.4

Basically the user controling the webhook needs to be part of the channel and in my case that wasn't so.  

All fixed!
